fujin:
  tls:
    server_cert_pem_path: /assets/certs/fujin.io.pem
    server_key_pem_path: /assets/certs/fujin.io-key.pem
connectors:
  writers:
    pub:
      protocol: kafka
      kafka:
        brokers: [kafka1:19092, kafka2:19093, kafka3:19094]
        topic: my_pub_topic
        allow_auto_topic_creation: true
  readers:
    sub:
      protocol: kafka
      kafka:
        brokers: [kafka1:19092, kafka2:19093, kafka3:19094]
        topic: my_pub_topic
        group: fujin
        allow_auto_topic_creation: true