fujin:
  tls:
    server_cert_pem_path: /assets/certs/fujin.io.pem
    server_key_pem_path: /assets/certs/fujin.io-key.pem
connectors:
  writers:
    pub:
      protocol: nats_core
      settings:
        url: nats://localhost:4222
        subject: my_subject
  readers:
    sub:
      protocol: nats_core
      settings:
        url: nats://localhost:4222
        subject: my_subject