fujin:
  enabled: true
  tls:
    enabled: true
    server_cert_pem_path: /assets/certs/fujin.io.pem
    server_key_pem_path: /assets/certs/fujin.io-key.pem
connectors:
  writers:
    pub:
      protocol: amqp10
      settings:
        conn:
          addr: amqp://artemis:artemis@localhost:61616
        sender:
          target: exchange
  readers:
    sub:
      protocol: amqp10
      settings:
        conn:
          addr: amqp://artemis:artemis@localhost:61616
        receiver:
          source: exchange
observability:
  metrics:
    enabled: true
    addr: ":9090"
    path: "/metrics"
  tracing:
    enabled: true
    otlp_endpoint: "otel-collector:4317"
    insecure: true
    sample_ratio: 0.1
    resource:
      service_name: "fujin"
      service_version: "dev"
      env: "dev"