fujin:
  tls:
    server_cert_pem_path: /assets/certs/fujin.io.pem
    server_key_pem_path: /assets/certs/fujin.io-key.pem
connectors:
  writers:
    pub:
      protocol: resp_pubsub
      settings:
        init_address: ["localhost:6379"]
        channel: example-channel
        batch_size: 1000
        linger: 10ms
  readers:
    sub:
      protocol: resp_pubsub
      settings:
        init_address: ["localhost:6379"]
        channel: example-channel