fujin:
  addr: :4848
  ping_interval: 5s
  ping_timeout: 10s
  ping_stream: false
  ping_max_retries: 5
  write_deadline: 10s
  force_terminate_timeout: 15s
  tls:
    server_cert_pem_path: ./resources/assets/certs/fujin.io.pem
    server_key_pem_path: ./resources/assets/certs/fujin.io-key.pem
  quic:
    max_incoming_streams: 1000
    max_idle_timeout: 5s
    keepalive_period: 2s
connectors:
  writers:
    pub:
      protocol: kafka
      settings:
        brokers: [localhost:9092, localhost:9093, localhost:9094]
        topic: my_pub_topic
        allow_auto_topic_creation: true
        linger: 10ms
        max_buffered_records: 10000
        disable_idempotent_write: false
    # pub:
    #   protocol: resp_pubsub
    #   settings:
    #     init_address: ["localhost:6379"]
    #     channel: example-channel
    #     batch_size: 1000
    #     linger: 10ms
    # pub:
    #   protocol: nats
    #   nats:
    #     url: nats://localhost:4222
    #     subject: my_subject
    # pub:
    #   protocol: amqp091
    #   settings:
    #     conn:
    #       url: amqp://guest:guest@localhost
    #     exchange:
    #       name: events
    #       kind: fanout
    #     queue:
    #       name: my_queue
    #     queue_bind:
    #       binding_key: my_routing_key
    #     publish:
    #       content_type: text/plain
    # pub:
    #   protocol: amqp10
    #   settings:
    #     conn:
    #       addr: amqp://artemis:artemis@localhost:61616
    #     sender:
    #       target: exchange
    # pub:
    #   protocol: resp_streams
    #   settings:
    #     init_address: ["localhost:6379"]
    #     stream: stream
    #     batch_size: 1000
    #     linger: 10ms
    #     # parse_msg_protocol: json
    # pub:
    #   protocol: mqtt
    #   settings:
    #     broker_url: tcp://localhost:1883
    #     client_id: fujin_pub
    #     topic: my_topic
    #     qos: 0
    #     retain: false
    #     clean_session: true
    #     keep_alive: 2s
    #     disconnect_timeout: 5s
    #     pool:
    #       size: 10000
    #       pre_alloc: true
    #       release_timeout: 5s
    # pub:
    #   protocol: nsq
    #   settings:
    #     address: "localhost:4150"
    #     topic: my_topic
    #     pool:
    #       size: 10000
    #       pre_alloc: true
    #       release_timeout: 5s
  readers:
    sub:
      protocol: kafka
      settings:
        brokers: [localhost:9092, localhost:9093, localhost:9094]
        topic: my_pub_topic
        group: fujin
        # allow_auto_topic_creation: true
        # max_poll_records: 10000
        # auto_commit_interval: 5s
        # auto_commit_marks: false
        # block_rebalance_on_poll: false
        # balancers:
        #   - round_robin # sticky/cooperative_sticky/range/round_robin (defaults to cooperative_sticky)
        # fetch_isolation_level: read_commited # read_commited/read_uncommited (defaults to read_uncommited)
    # sub:
    #   protocol: nats
    #   nats:
    #     url: nats://localhost:4222
    #     subject: my_subject
    # sub:
    #   protocol: amqp091
    #   settings:
    #     conn:
    #       url: amqp://guest:guest@localhost
    #     exchange:
    #       name: events
    #       kind: fanout
    #     queue:
    #       name: my_queue
    #     queue_bind:
    #       routing_key: my_routing_key
    #     consume:
    #       consumer: fujin
    #     nack:
    #       requeue: true
    # sub:
    #   protocol: amqp10
    #   settings:
    #     conn:
    #       addr: amqp://artemis:artemis@localhost:61616
    #     receiver:
    #       source: exchange
    # sub:
    #   protocol: resp_pubsub
    #   settings:
    #     init_address: ["localhost:6379"]
    #     channels: [example-channel]
    # sub:
    #   protocol: resp_streams
    #   settings:
    #     init_address: ["localhost:6379"]
    #     group:
    #       name: fujin
    #       consumer: fujin
    #     streams:
    #       stream:
    #         group_create_id: $
    #         start_id: ">"
    #     block: 3s
    #     # parse_msg_protocol: json
    # sub:
    #   protocol: mqtt
    #   settings:
    #     broker_url: tcp://localhost:1883
    #     client_id: fujin_sub
    #     topic: my_topic
    #     qos: 0
    #     retain: false
    #     clean_session: true
    #     keep_alive: 2s
    #     disconnect_timeout: 5s
    # sub:
    #   protocol: nsq
    #   settings:
    #     addresses: ["localhost:4150"]
    #     # lookupd_addresses: ["localhost:4161"]
    #     topic: my_topic
    #     channel: my_channel
    #     max_in_flight: 1000000
