// Package fujin loads and controls Fujin libraries generated by cargo-fujin.
package fujin

/*
#cgo linux LDFLAGS: -ldl
#include <stdlib.h>
#include "bridge.h"
*/
import "C"

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"runtime"
	"sync"
	"unsafe"
)

const (
	// ABIVersion is the C ABI revision required by this SDK.
	ABIVersion = 1

	// StatusOK reports successful completion.
	StatusOK = 0
	// StatusInvalidArgument reports malformed input or an invalid ABI pointer.
	StatusInvalidArgument = 1
	// StatusStartFailed reports application compilation, listener, or readiness failure.
	StatusStartFailed = 2
	// StatusRuntimeFailed reports a control or shutdown failure after startup.
	StatusRuntimeFailed = 3
	// StatusPanic reports a Rust panic caught at the ABI boundary.
	StatusPanic = 255
)

// ErrClosed is returned when an operation targets a closed application or library.
var ErrClosed = errors.New("fujin: closed")

// StatusError reports a failure returned by the Fujin C ABI.
type StatusError struct {
	Status  int
	Message string
}

func (e *StatusError) Error() string {
	return fmt.Sprintf("fujin: status %d: %s", e.Status, e.Message)
}

// Library is one dynamically loaded Fujin library.
// Close the library after every application created from it has been closed.
type Library struct {
	mu      sync.Mutex
	native  *C.FujinLibrary
	active  int
	version string
}

// Open loads a cargo-fujin generated library and validates its ABI revision.
func Open(path string) (*Library, error) {
	encoded := C.CString(path)
	defer C.free(unsafe.Pointer(encoded))
	const errorCapacity = 4096
	message := (*C.char)(C.malloc(errorCapacity))
	if message == nil {
		return nil, errors.New("fujin: allocate loader error buffer")
	}
	defer C.free(unsafe.Pointer(message))
	library := C.fujin_library_open(encoded, message, errorCapacity)
	if library == nil {
		return nil, errors.New(C.GoString(message))
	}
	if version := uint32(C.fujin_call_abi_version(library)); version != ABIVersion {
		C.fujin_library_close(library)
		return nil, fmt.Errorf("fujin: unsupported ABI version %d, expected %d", version, ABIVersion)
	}
	return &Library{
		native:  library,
		version: C.GoString(C.fujin_call_build_version(library)),
	}, nil
}

// BuildVersion returns the generated library's package version.
func (l *Library) BuildVersion() string {
	return l.version
}

// Close unloads the library. It rejects libraries with active applications.
func (l *Library) Close() error {
	l.mu.Lock()
	defer l.mu.Unlock()
	if l.native == nil {
		return nil
	}
	if l.active != 0 {
		return fmt.Errorf("fujin: close library with %d active applications", l.active)
	}
	C.fujin_library_close(l.native)
	l.native = nil
	return nil
}

// Start starts an application and waits until its configured listeners are ready.
// If ctx expires while native startup is in progress, Start returns immediately and
// closes the application asynchronously once startup completes.
func (l *Library) Start(ctx context.Context, options Options) (*Application, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	request, err := encodeStartRequest(options)
	if err != nil {
		return nil, err
	}
	l.mu.Lock()
	if l.native == nil {
		l.mu.Unlock()
		return nil, ErrClosed
	}
	l.active++
	native := l.native
	l.mu.Unlock()

	result := make(chan startResult, 1)
	go func() {
		var handle *C.FujinHandle
		var nativeError *C.FujinError
		status := C.fujin_call_start(
			native,
			bytesPointer(request),
			C.size_t(len(request)),
			&handle,
			&nativeError,
		)
		runtime.KeepAlive(request)
		if err := l.statusError(native, status, nativeError); err != nil {
			l.release()
			result <- startResult{err: err}
			return
		}
		result <- startResult{application: &Application{
			library: l,
			native:  native,
			handle:  handle,
			done:    make(chan struct{}),
		}}
	}()

	select {
	case started := <-result:
		return started.application, started.err
	case <-ctx.Done():
		go func() {
			started := <-result
			if started.application != nil {
				_ = started.application.Close()
			}
		}()
		return nil, ctx.Err()
	}
}

type startResult struct {
	application *Application
	err         error
}

// Application controls one running embedded Fujin application.
// Close must be called to release the native handle and its reference to Library.
type Application struct {
	library *Library
	native  *C.FujinLibrary

	mu     sync.RWMutex
	handle *C.FujinHandle

	waitOnce sync.Once
	done     chan struct{}
	waitErr  error
}

// Endpoints returns the addresses of listeners that completed startup.
func (a *Application) Endpoints() ([]Endpoint, error) {
	var endpoints []Endpoint
	err := a.readJSON(func(handle *C.FujinHandle, output *C.FujinBuffer, nativeError **C.FujinError) C.int32_t {
		return C.fujin_call_endpoints_json(a.native, handle, output, nativeError)
	}, &endpoints)
	return endpoints, err
}

// Status returns the current connector runtime and catalog status.
func (a *Application) Status() (RuntimeStatus, error) {
	var status RuntimeStatus
	err := a.readJSON(func(handle *C.FujinHandle, output *C.FujinBuffer, nativeError **C.FujinError) C.int32_t {
		return C.fujin_call_runtime_status_json(a.native, handle, output, nativeError)
	}, &status)
	return status, err
}

// WatchesConnectors reports whether the selected configurator owns runtime connector state.
func (a *Application) WatchesConnectors() (bool, error) {
	a.mu.RLock()
	defer a.mu.RUnlock()
	if a.handle == nil {
		return false, ErrClosed
	}
	var output C.uint8_t
	var nativeError *C.FujinError
	status := C.fujin_call_watches_connectors(a.native, a.handle, &output, &nativeError)
	if err := a.library.statusError(a.native, status, nativeError); err != nil {
		return false, err
	}
	return output != 0, nil
}

// ReloadConnectors submits one complete connector snapshot.
func (a *Application) ReloadConnectors(snapshot ConnectorSnapshot) (ApplyResult, error) {
	request, err := json.Marshal(snapshot)
	if err != nil {
		return ApplyResult{}, fmt.Errorf("fujin: encode connector snapshot: %w", err)
	}
	var result ApplyResult
	err = a.readJSON(func(handle *C.FujinHandle, output *C.FujinBuffer, nativeError **C.FujinError) C.int32_t {
		return C.fujin_call_reload_connectors_json(
			a.native,
			handle,
			bytesPointer(request),
			C.size_t(len(request)),
			output,
			nativeError,
		)
	}, &result)
	return result, err
}

// ReloadFromConfigurator reloads connectors through the retained bootstrap configurator.
func (a *Application) ReloadFromConfigurator() (ApplyResult, error) {
	var result ApplyResult
	err := a.readJSON(func(handle *C.FujinHandle, output *C.FujinBuffer, nativeError **C.FujinError) C.int32_t {
		return C.fujin_call_reload_from_configurator_json(a.native, handle, output, nativeError)
	}, &result)
	return result, err
}

// RequestShutdown requests graceful application shutdown without waiting for completion.
func (a *Application) RequestShutdown() error {
	a.mu.RLock()
	defer a.mu.RUnlock()
	if a.handle == nil {
		return ErrClosed
	}
	var nativeError *C.FujinError
	status := C.fujin_call_shutdown(a.native, a.handle, &nativeError)
	return a.library.statusError(a.native, status, nativeError)
}

// Wait blocks until the application terminates and returns its terminal error.
func (a *Application) Wait() error {
	<-a.Done()
	return a.waitErr
}

// Done returns a channel closed when the application terminates.
func (a *Application) Done() <-chan struct{} {
	a.waitOnce.Do(func() {
		go func() {
			a.mu.RLock()
			defer a.mu.RUnlock()
			if a.handle == nil {
				a.waitErr = ErrClosed
				close(a.done)
				return
			}
			var nativeError *C.FujinError
			status := C.fujin_call_wait(a.native, a.handle, &nativeError)
			a.waitErr = a.library.statusError(a.native, status, nativeError)
			close(a.done)
		}()
	})
	return a.done
}

// Shutdown requests graceful shutdown and waits until termination or ctx cancellation.
// The native handle remains allocated; call Close afterward.
func (a *Application) Shutdown(ctx context.Context) error {
	if err := a.RequestShutdown(); err != nil && !errors.Is(err, ErrClosed) {
		return err
	}
	select {
	case <-a.Done():
		return a.waitErr
	case <-ctx.Done():
		return ctx.Err()
	}
}

// Close requests shutdown, waits without a deadline, and releases the native handle.
// Call Shutdown with a bounded context first when shutdown latency must be bounded.
func (a *Application) Close() error {
	shutdownErr := a.RequestShutdown()
	waitErr := a.Wait()
	a.mu.Lock()
	if a.handle == nil {
		a.mu.Unlock()
		return nil
	}
	handle := a.handle
	a.handle = nil
	var nativeError *C.FujinError
	status := C.fujin_call_free(a.native, handle, &nativeError)
	freeErr := a.library.statusError(a.native, status, nativeError)
	a.mu.Unlock()
	a.library.release()
	return errors.Join(ignoreClosed(shutdownErr), ignoreClosed(waitErr), freeErr)
}

type jsonCall func(*C.FujinHandle, *C.FujinBuffer, **C.FujinError) C.int32_t

func (a *Application) readJSON(call jsonCall, output any) error {
	a.mu.RLock()
	defer a.mu.RUnlock()
	if a.handle == nil {
		return ErrClosed
	}
	var buffer C.FujinBuffer
	var nativeError *C.FujinError
	status := call(a.handle, &buffer, &nativeError)
	if err := a.library.statusError(a.native, status, nativeError); err != nil {
		return err
	}
	defer C.fujin_call_buffer_free(a.native, buffer)
	if uint64(buffer.length) > uint64(math.MaxInt32) {
		return errors.New("fujin: ABI output exceeds Go addressable memory")
	}
	encoded := C.GoBytes(unsafe.Pointer(buffer.data), C.int(buffer.length))
	if err := json.Unmarshal(encoded, output); err != nil {
		return fmt.Errorf("fujin: decode ABI response: %w", err)
	}
	return nil
}

func (l *Library) statusError(native *C.FujinLibrary, status C.int32_t, nativeError *C.FujinError) error {
	if status == 0 {
		if nativeError != nil {
			C.fujin_call_error_free(native, nativeError)
		}
		return nil
	}
	message := "unknown error"
	if nativeError != nil {
		if encoded := C.fujin_call_error_message(native, nativeError); encoded != nil {
			message = C.GoString(encoded)
		}
		C.fujin_call_error_free(native, nativeError)
	}
	return &StatusError{Status: int(status), Message: message}
}

func (l *Library) release() {
	l.mu.Lock()
	l.active--
	l.mu.Unlock()
}

func encodeStartRequest(options Options) ([]byte, error) {
	if options.WorkerThreads < 0 {
		return nil, errors.New("fujin: worker threads must not be negative")
	}
	type runtimeRequest struct {
		WorkerThreads *int   `json:"worker_threads,omitempty"`
		ThreadName    string `json:"thread_name,omitempty"`
	}
	type startRequest struct {
		Config          *RuntimeConfig `json:"config,omitempty"`
		Runtime         runtimeRequest `json:"runtime,omitempty"`
		GracefulUpgrade bool           `json:"graceful_upgrade"`
	}
	var workers *int
	if options.WorkerThreads != 0 {
		workers = &options.WorkerThreads
	}
	request, err := json.Marshal(startRequest{
		Config: options.Config,
		Runtime: runtimeRequest{
			WorkerThreads: workers,
			ThreadName:    options.RuntimeThread,
		},
		GracefulUpgrade: options.GracefulUpgrade,
	})
	if err != nil {
		return nil, fmt.Errorf("fujin: encode start request: %w", err)
	}
	return request, nil
}
func ignoreClosed(err error) error {
	if errors.Is(err, ErrClosed) {
		return nil
	}
	return err
}

func bytesPointer(value []byte) *C.uint8_t {
	if len(value) == 0 {
		return nil
	}
	return (*C.uint8_t)(unsafe.Pointer(&value[0]))
}
