[package]
name = "fujin-transport"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
fujin-connector = { path = "../fujin-connector" }
fujin-middleware = { path = "../fujin-middleware" }
fujin-native = { path = "../fujin-native" }
fujin-upgrade = { path = "../fujin-upgrade" }
parking_lot.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tokio-util.workspace = true
tracing.workspace = true
