[package]
name = "fujin-configurator-file"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "YAML and JSON file configurator plugin for Fujin"
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
fujin-configurator.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
yaml_serde.workspace = true
