[package]
name = "fujin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
default = []
grpc = ["fujin-runtime/grpc"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
fujin-configurator = { path = "../fujin-configurator" }
fujin-connector = { path = "../fujin-connector" }
fujin-error = { path = "../fujin-error" }
fujin-runtime = { path = "../fujin-runtime" }
fujin-middleware = { path = "../fujin-middleware" }
fujin-native = { path = "../fujin-native" }
fujin-transport = { path = "../fujin-transport" }
tokio.workspace = true
tokio-util.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

[dev-dependencies]
serde_json.workspace = true
yaml_serde.workspace = true
fujin-transport-tcp = { path = "../../plugins/transport/tcp" }
