fujin:
  transports:
    - type: tcp
      settings:
        addr: 0.0.0.0:4850
grpc:
  enabled: false
health:
  enabled: true
  addr: 0.0.0.0:8080
connectors:
  connector:
    type: kafka
    settings:
      common:
        brokers: [kafka1:19092, kafka2:19093, kafka3:19094]
        properties: {}
      routes:
        pub:
          produce_topic: my_pub_topic
          properties:
            allow.auto.create.topics: "true"
        sub:
          consume_topics: [my_pub_topic]
          group: fujin
          properties:
            auto.offset.reset: earliest
            allow.auto.create.topics: "true"
