[package]
name = "fujin-transport-quic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
fujin-core = { path = "../../crates/fujin-core" }
fujin-runtime = { path = "../../crates/fujin-runtime" }
fujin-tls = { path = "../../crates/fujin-tls" }
fujin-transport = { path = "../../crates/fujin-transport" }
fujin-upgrade = { path = "../../crates/fujin-upgrade" }
futures-util.workspace = true
humantime.workspace = true
quinn.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
