[package]
name = "fujin-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
default = []
grpc = ["dep:fujin-proto", "dep:tokio-stream", "dep:tonic", "dep:tonic-health", "dep:tonic-prost"]

[dependencies]
anyhow.workspace = true
arc-swap.workspace = true
async-trait.workspace = true
bytes.workspace = true
fujin-core = { path = "../fujin-core" }
fujin-proto = { path = "../fujin-proto", optional = true }
fujin-tls = { path = "../fujin-tls" }
fujin-transport = { path = "../fujin-transport" }
fujin-upgrade = { path = "../fujin-upgrade" }
humantime.workspace = true
parking_lot.workspace = true
prost.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream = { workspace = true, optional = true }
tokio-util.workspace = true
tonic = { workspace = true, optional = true }
tonic-health = { workspace = true, optional = true }
tonic-prost = { workspace = true, optional = true }
tracing.workspace = true

[dev-dependencies]
fujin-native = { path = "../fujin-native" }
