[package]
name = "fujin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
default = []
full = [
    "configurator-env",
    "configurator-yaml",
    "kafka",
    "tcp",
    "unix",
    "websocket",
    "quic",
    "grpc",
]
configurator-env = []
configurator-yaml = []
kafka = ["dep:fujin-kafka", "fujin-kafka/rdkafka"]
tcp = ["fujin-server/tcp"]
unix = ["fujin-server/unix"]
websocket = ["fujin-server/websocket"]
quic = ["fujin-server/quic"]
grpc = ["fujin-server/grpc"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
fujin-core = { path = "../fujin-core" }
fujin-kafka = { path = "../fujin-kafka", optional = true }
fujin-plugin-api = { path = "../fujin-plugin-api" }
fujin-runtime = { path = "../fujin-runtime" }
fujin-server = { path = "../fujin-server", default-features = false }
fujin-upgrade = { path = "../fujin-upgrade" }
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
serde_json.workspace = true
yaml_serde.workspace = true
