[package]
name = "fujin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
default = []
full = [
    "configurator-env",
    "configurator-yaml",
    "kafka",
    "tcp",
    "unix",
    "websocket",
    "quic",
    "grpc",
]
configurator-env = ["dep:fujin-configurator-env"]
configurator-yaml = ["dep:fujin-configurator-yaml"]
kafka = ["dep:fujin-connector-kafka"]
tcp = ["dep:fujin-transport-tcp"]
unix = ["dep:fujin-transport-unix"]
websocket = ["dep:fujin-transport-websocket"]
quic = ["dep:fujin-transport-quic"]
grpc = ["fujin-runtime/grpc"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
fujin-core = { path = "../fujin-core" }
fujin-configurator-env = { path = "../../plugins/configurator/env", optional = true }
fujin-configurator-yaml = { path = "../../plugins/configurator/yaml", optional = true }
fujin-connector-kafka = { path = "../../plugins/connector/kafka", optional = true }
fujin-plugin-api = { path = "../fujin-plugin-api" }
fujin-runtime = { path = "../fujin-runtime" }
fujin-transport = { path = "../fujin-transport" }
fujin-transport-quic = { path = "../../plugins/transport/quic", optional = true }
fujin-transport-tcp = { path = "../../plugins/transport/tcp", optional = true }
fujin-transport-unix = { path = "../../plugins/transport/unix", optional = true }
fujin-transport-websocket = { path = "../../plugins/transport/websocket", optional = true }
fujin-upgrade = { path = "../fujin-upgrade" }
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true


[dev-dependencies]
serde_json.workspace = true
yaml_serde.workspace = true

[[example]]
name = "embed"
required-features = ["tcp"]
