[package]
name = "fujin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
default = []
full = [
    "configurator-env",
    "configurator-yaml",
    "kafka",
    "tcp",
    "unix",
    "websocket",
    "quic",
    "grpc",
]
configurator-env = ["dep:fujin-configurators", "fujin-configurators/env"]
configurator-yaml = ["dep:fujin-configurators", "fujin-configurators/yaml"]
kafka = ["dep:fujin-kafka", "fujin-kafka/rdkafka"]
tcp = ["dep:fujin-transports", "fujin-transports/tcp"]
unix = ["dep:fujin-transports", "fujin-transports/unix"]
websocket = ["dep:fujin-transports", "fujin-transports/websocket"]
quic = ["dep:fujin-transports", "fujin-transports/quic"]
grpc = ["fujin-runtime/grpc"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
fujin-core = { path = "../fujin-core" }
fujin-configurators = { path = "../../plugins/configurators", optional = true }
fujin-kafka = { path = "../fujin-kafka", optional = true }
fujin-plugin-api = { path = "../fujin-plugin-api" }
fujin-runtime = { path = "../fujin-runtime" }
fujin-transport = { path = "../fujin-transport" }
fujin-transports = { path = "../../plugins/transports", optional = true }
fujin-upgrade = { path = "../fujin-upgrade" }
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true


[dev-dependencies]
serde_json.workspace = true
yaml_serde.workspace = true

[[example]]
name = "embed"
required-features = ["tcp"]
