[package]
name = "fujin-configurator-env"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
fujin-configurator = { path = "../../../crates/fujin-configurator" }
serde_json.workspace = true
tracing.workspace = true
yaml_serde.workspace = true
