package response

type ErrCode byte

const (
	ERR_CODE_NO = iota
	ERR_CODE_PRODUCE
	ERR_CODE_CONNECT_SUBSCRIBER
	ERR_CODE_CONNECT_CONSUMER
)

type RespCode byte

const (
	RESP_CODE_UNKNOWN RespCode = iota
	// Client response opcodes
	RESP_CODE_PONG

	// Server response opcodes
	RESP_CODE_CONNECT_READER
	RESP_CODE_PRODUCE
	RESP_CODE_MSG
	RESP_CODE_ACK
	RESP_CODE_NACK
	RESP_CODE_TX_BEGIN
	RESP_CODE_TX_COMMIT
	RESP_CODE_TX_ROLLBACK

	RESP_CODE_DISCONNECT
	RESP_CODE_STOP
)

var (
	DISCONNECT_RESP = []byte{
		byte(RESP_CODE_DISCONNECT), // cmd (8)
	}
	STOP_RESP = []byte{
		byte(RESP_CODE_STOP), // cmd (9)
	}
)
