package request

type OpCode byte

const (
	OP_CODE_UNKNOWN OpCode = iota

	// Client request opcodes
	OP_CODE_CONNECT_PRODUCER
	OP_CODE_CONNECT_SUBSCRIBER
	OP_CODE_CONNECT_CONSUMER
	OP_CODE_PRODUCE
	OP_CODE_TX_BEGIN
	OP_CODE_TX_COMMIT
	OP_CODE_TX_ROLLBACK
	OP_CODE_CONSUME
	OP_CODE_ACK
	OP_CODE_NACK
	OP_CODE_DISCONNECT

	// Server request opcodes
	OP_CODE_PING
)
