[package]
name = "fujin-native"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
bytes.workspace = true
fujin-connector = { path = "../fujin-connector" }
fujin-core = { path = "../fujin-core" }
fujin-error = { path = "../fujin-error" }
fujin-middleware = { path = "../fujin-middleware" }
fujin-transport = { path = "../fujin-transport" }
parking_lot.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
