// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: public/grpc/v1/fujin.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Binary-safe header, matching [][]byte in native protocol.
type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_public_grpc_v1_fujin_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Header) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Connect request - must be sent first to initialize the stream
type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId uint32                 `protobuf:"varint,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"` // Used as transactional ID for Kafka
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_public_grpc_v1_fujin_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectRequest) GetCorrelationId() uint32 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *ConnectRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

// Connect response
type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId uint32                 `protobuf:"varint,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_public_grpc_v1_fujin_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectResponse) GetCorrelationId() uint32 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *ConnectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Produce request with correlation ID for async response matching
type ProduceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId uint32                 `protobuf:"varint,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Message       []byte                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Headers       []*Header              `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceRequest) Reset() {
	*x = ProduceRequest{}
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceRequest) ProtoMessage() {}

func (x *ProduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceRequest.ProtoReflect.Descriptor instead.
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return file_public_grpc_v1_fujin_proto_rawDescGZIP(), []int{3}
}

func (x *ProduceRequest) GetCorrelationId() uint32 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *ProduceRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ProduceRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ProduceRequest) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

// Produce response with correlation ID
type ProduceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId uint32                 `protobuf:"varint,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceResponse) Reset() {
	*x = ProduceResponse{}
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceResponse) ProtoMessage() {}

func (x *ProduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceResponse.ProtoReflect.Descriptor instead.
func (*ProduceResponse) Descriptor() ([]byte, []int) {
	return file_public_grpc_v1_fujin_proto_rawDescGZIP(), []int{4}
}

func (x *ProduceResponse) GetCorrelationId() uint32 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *ProduceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Subscribe request
type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId uint32                 `protobuf:"varint,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	AutoCommit    bool                   `protobuf:"varint,3,opt,name=auto_commit,json=autoCommit,proto3" json:"auto_commit,omitempty"`
	Headers       []*Header              `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_public_grpc_v1_fujin_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeRequest) GetCorrelationId() uint32 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *SubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscribeRequest) GetAutoCommit() bool {
	if x != nil {
		return x.AutoCommit
	}
	return false
}

func (x *SubscribeRequest) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

// Subscribe response
type SubscribeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId  uint32                 `protobuf:"varint,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Error          string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	SubscriptionId uint32                 `protobuf:"varint,3,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"` // Limited to 0-255 (byte) to match native protocol, but protobuf requires uint32
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_public_grpc_v1_fujin_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeResponse) GetCorrelationId() uint32 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *SubscribeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SubscribeResponse) GetSubscriptionId() uint32 {
	if x != nil {
		return x.SubscriptionId
	}
	return 0
}

// Unsubscribe request
type UnsubscribeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId  uint32                 `protobuf:"varint,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	SubscriptionId uint32                 `protobuf:"varint,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_public_grpc_v1_fujin_proto_rawDescGZIP(), []int{7}
}

func (x *UnsubscribeRequest) GetCorrelationId() uint32 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *UnsubscribeRequest) GetSubscriptionId() uint32 {
	if x != nil {
		return x.SubscriptionId
	}
	return 0
}

// Unsubscribe response
type UnsubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId uint32                 `protobuf:"varint,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeResponse) Reset() {
	*x = UnsubscribeResponse{}
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeResponse) ProtoMessage() {}

func (x *UnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) {
	return file_public_grpc_v1_fujin_proto_rawDescGZIP(), []int{8}
}

func (x *UnsubscribeResponse) GetCorrelationId() uint32 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *UnsubscribeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Message delivery
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId uint32                 `protobuf:"varint,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers       []*Header              `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
	DeliveryId    []byte                 `protobuf:"bytes,5,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_public_grpc_v1_fujin_proto_rawDescGZIP(), []int{9}
}

func (x *Message) GetCorrelationId() uint32 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *Message) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Message) GetDeliveryId() []byte {
	if x != nil {
		return x.DeliveryId
	}
	return nil
}

// Ack request
type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId uint32                 `protobuf:"varint,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	MessageId     []byte                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_public_grpc_v1_fujin_proto_rawDescGZIP(), []int{10}
}

func (x *AckRequest) GetCorrelationId() uint32 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *AckRequest) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

// Nack request
type NackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId uint32                 `protobuf:"varint,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	MessageId     []byte                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackRequest) Reset() {
	*x = NackRequest{}
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackRequest) ProtoMessage() {}

func (x *NackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackRequest.ProtoReflect.Descriptor instead.
func (*NackRequest) Descriptor() ([]byte, []int) {
	return file_public_grpc_v1_fujin_proto_rawDescGZIP(), []int{11}
}

func (x *NackRequest) GetCorrelationId() uint32 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *NackRequest) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

// Empty response
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId uint32                 `protobuf:"varint,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_public_grpc_v1_fujin_proto_rawDescGZIP(), []int{12}
}

func (x *Empty) GetCorrelationId() uint32 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

func (x *Empty) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Union type for all requests
type FujinRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*FujinRequest_Connect
	//	*FujinRequest_Produce
	//	*FujinRequest_Subscribe
	//	*FujinRequest_Unsubscribe
	//	*FujinRequest_Ack
	//	*FujinRequest_Nack
	Request       isFujinRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FujinRequest) Reset() {
	*x = FujinRequest{}
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FujinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FujinRequest) ProtoMessage() {}

func (x *FujinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FujinRequest.ProtoReflect.Descriptor instead.
func (*FujinRequest) Descriptor() ([]byte, []int) {
	return file_public_grpc_v1_fujin_proto_rawDescGZIP(), []int{13}
}

func (x *FujinRequest) GetRequest() isFujinRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *FujinRequest) GetConnect() *ConnectRequest {
	if x != nil {
		if x, ok := x.Request.(*FujinRequest_Connect); ok {
			return x.Connect
		}
	}
	return nil
}

func (x *FujinRequest) GetProduce() *ProduceRequest {
	if x != nil {
		if x, ok := x.Request.(*FujinRequest_Produce); ok {
			return x.Produce
		}
	}
	return nil
}

func (x *FujinRequest) GetSubscribe() *SubscribeRequest {
	if x != nil {
		if x, ok := x.Request.(*FujinRequest_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *FujinRequest) GetUnsubscribe() *UnsubscribeRequest {
	if x != nil {
		if x, ok := x.Request.(*FujinRequest_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

func (x *FujinRequest) GetAck() *AckRequest {
	if x != nil {
		if x, ok := x.Request.(*FujinRequest_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *FujinRequest) GetNack() *NackRequest {
	if x != nil {
		if x, ok := x.Request.(*FujinRequest_Nack); ok {
			return x.Nack
		}
	}
	return nil
}

type isFujinRequest_Request interface {
	isFujinRequest_Request()
}

type FujinRequest_Connect struct {
	Connect *ConnectRequest `protobuf:"bytes,1,opt,name=connect,proto3,oneof"`
}

type FujinRequest_Produce struct {
	Produce *ProduceRequest `protobuf:"bytes,2,opt,name=produce,proto3,oneof"`
}

type FujinRequest_Subscribe struct {
	Subscribe *SubscribeRequest `protobuf:"bytes,3,opt,name=subscribe,proto3,oneof"`
}

type FujinRequest_Unsubscribe struct {
	Unsubscribe *UnsubscribeRequest `protobuf:"bytes,4,opt,name=unsubscribe,proto3,oneof"`
}

type FujinRequest_Ack struct {
	Ack *AckRequest `protobuf:"bytes,5,opt,name=ack,proto3,oneof"`
}

type FujinRequest_Nack struct {
	Nack *NackRequest `protobuf:"bytes,6,opt,name=nack,proto3,oneof"`
}

func (*FujinRequest_Connect) isFujinRequest_Request() {}

func (*FujinRequest_Produce) isFujinRequest_Request() {}

func (*FujinRequest_Subscribe) isFujinRequest_Request() {}

func (*FujinRequest_Unsubscribe) isFujinRequest_Request() {}

func (*FujinRequest_Ack) isFujinRequest_Request() {}

func (*FujinRequest_Nack) isFujinRequest_Request() {}

// Union type for all responses
type FujinResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*FujinResponse_Connect
	//	*FujinResponse_Produce
	//	*FujinResponse_Subscribe
	//	*FujinResponse_Unsubscribe
	//	*FujinResponse_Message
	//	*FujinResponse_Ack
	//	*FujinResponse_Nack
	Response      isFujinResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FujinResponse) Reset() {
	*x = FujinResponse{}
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FujinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FujinResponse) ProtoMessage() {}

func (x *FujinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_grpc_v1_fujin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FujinResponse.ProtoReflect.Descriptor instead.
func (*FujinResponse) Descriptor() ([]byte, []int) {
	return file_public_grpc_v1_fujin_proto_rawDescGZIP(), []int{14}
}

func (x *FujinResponse) GetResponse() isFujinResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *FujinResponse) GetConnect() *ConnectResponse {
	if x != nil {
		if x, ok := x.Response.(*FujinResponse_Connect); ok {
			return x.Connect
		}
	}
	return nil
}

func (x *FujinResponse) GetProduce() *ProduceResponse {
	if x != nil {
		if x, ok := x.Response.(*FujinResponse_Produce); ok {
			return x.Produce
		}
	}
	return nil
}

func (x *FujinResponse) GetSubscribe() *SubscribeResponse {
	if x != nil {
		if x, ok := x.Response.(*FujinResponse_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *FujinResponse) GetUnsubscribe() *UnsubscribeResponse {
	if x != nil {
		if x, ok := x.Response.(*FujinResponse_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

func (x *FujinResponse) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Response.(*FujinResponse_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *FujinResponse) GetAck() *Empty {
	if x != nil {
		if x, ok := x.Response.(*FujinResponse_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *FujinResponse) GetNack() *Empty {
	if x != nil {
		if x, ok := x.Response.(*FujinResponse_Nack); ok {
			return x.Nack
		}
	}
	return nil
}

type isFujinResponse_Response interface {
	isFujinResponse_Response()
}

type FujinResponse_Connect struct {
	Connect *ConnectResponse `protobuf:"bytes,1,opt,name=connect,proto3,oneof"`
}

type FujinResponse_Produce struct {
	Produce *ProduceResponse `protobuf:"bytes,2,opt,name=produce,proto3,oneof"`
}

type FujinResponse_Subscribe struct {
	Subscribe *SubscribeResponse `protobuf:"bytes,3,opt,name=subscribe,proto3,oneof"`
}

type FujinResponse_Unsubscribe struct {
	Unsubscribe *UnsubscribeResponse `protobuf:"bytes,4,opt,name=unsubscribe,proto3,oneof"`
}

type FujinResponse_Message struct {
	Message *Message `protobuf:"bytes,5,opt,name=message,proto3,oneof"`
}

type FujinResponse_Ack struct {
	Ack *Empty `protobuf:"bytes,6,opt,name=ack,proto3,oneof"`
}

type FujinResponse_Nack struct {
	Nack *Empty `protobuf:"bytes,7,opt,name=nack,proto3,oneof"`
}

func (*FujinResponse_Connect) isFujinResponse_Response() {}

func (*FujinResponse_Produce) isFujinResponse_Response() {}

func (*FujinResponse_Subscribe) isFujinResponse_Response() {}

func (*FujinResponse_Unsubscribe) isFujinResponse_Response() {}

func (*FujinResponse_Message) isFujinResponse_Response() {}

func (*FujinResponse_Ack) isFujinResponse_Response() {}

func (*FujinResponse_Nack) isFujinResponse_Response() {}

var File_public_grpc_v1_fujin_proto protoreflect.FileDescriptor

const file_public_grpc_v1_fujin_proto_rawDesc = "" +
	"\n" +
	"\x1apublic/grpc/v1/fujin.proto\x12\bfujin.v1\"0\n" +
	"\x06Header\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"T\n" +
	"\x0eConnectRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\rR\rcorrelationId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\"N\n" +
	"\x0fConnectResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\rR\rcorrelationId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x93\x01\n" +
	"\x0eProduceRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\rR\rcorrelationId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x18\n" +
	"\amessage\x18\x03 \x01(\fR\amessage\x12*\n" +
	"\aheaders\x18\x04 \x03(\v2\x10.fujin.v1.HeaderR\aheaders\"N\n" +
	"\x0fProduceResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\rR\rcorrelationId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x9c\x01\n" +
	"\x10SubscribeRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\rR\rcorrelationId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1f\n" +
	"\vauto_commit\x18\x03 \x01(\bR\n" +
	"autoCommit\x12*\n" +
	"\aheaders\x18\x04 \x03(\v2\x10.fujin.v1.HeaderR\aheaders\"y\n" +
	"\x11SubscribeResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\rR\rcorrelationId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12'\n" +
	"\x0fsubscription_id\x18\x03 \x01(\rR\x0esubscriptionId\"d\n" +
	"\x12UnsubscribeRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\rR\rcorrelationId\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\rR\x0esubscriptionId\"R\n" +
	"\x13UnsubscribeResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\rR\rcorrelationId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xad\x01\n" +
	"\aMessage\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\rR\rcorrelationId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12*\n" +
	"\aheaders\x18\x04 \x03(\v2\x10.fujin.v1.HeaderR\aheaders\x12\x1f\n" +
	"\vdelivery_id\x18\x05 \x01(\fR\n" +
	"deliveryId\"R\n" +
	"\n" +
	"AckRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\rR\rcorrelationId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\fR\tmessageId\"S\n" +
	"\vNackRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\rR\rcorrelationId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\fR\tmessageId\"D\n" +
	"\x05Empty\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\rR\rcorrelationId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xda\x02\n" +
	"\fFujinRequest\x124\n" +
	"\aconnect\x18\x01 \x01(\v2\x18.fujin.v1.ConnectRequestH\x00R\aconnect\x124\n" +
	"\aproduce\x18\x02 \x01(\v2\x18.fujin.v1.ProduceRequestH\x00R\aproduce\x12:\n" +
	"\tsubscribe\x18\x03 \x01(\v2\x1a.fujin.v1.SubscribeRequestH\x00R\tsubscribe\x12@\n" +
	"\vunsubscribe\x18\x04 \x01(\v2\x1c.fujin.v1.UnsubscribeRequestH\x00R\vunsubscribe\x12(\n" +
	"\x03ack\x18\x05 \x01(\v2\x14.fujin.v1.AckRequestH\x00R\x03ack\x12+\n" +
	"\x04nack\x18\x06 \x01(\v2\x15.fujin.v1.NackRequestH\x00R\x04nackB\t\n" +
	"\arequest\"\x84\x03\n" +
	"\rFujinResponse\x125\n" +
	"\aconnect\x18\x01 \x01(\v2\x19.fujin.v1.ConnectResponseH\x00R\aconnect\x125\n" +
	"\aproduce\x18\x02 \x01(\v2\x19.fujin.v1.ProduceResponseH\x00R\aproduce\x12;\n" +
	"\tsubscribe\x18\x03 \x01(\v2\x1b.fujin.v1.SubscribeResponseH\x00R\tsubscribe\x12A\n" +
	"\vunsubscribe\x18\x04 \x01(\v2\x1d.fujin.v1.UnsubscribeResponseH\x00R\vunsubscribe\x12-\n" +
	"\amessage\x18\x05 \x01(\v2\x11.fujin.v1.MessageH\x00R\amessage\x12#\n" +
	"\x03ack\x18\x06 \x01(\v2\x0f.fujin.v1.EmptyH\x00R\x03ack\x12%\n" +
	"\x04nack\x18\a \x01(\v2\x0f.fujin.v1.EmptyH\x00R\x04nackB\n" +
	"\n" +
	"\bresponse2M\n" +
	"\fFujinService\x12=\n" +
	"\x06Stream\x12\x16.fujin.v1.FujinRequest\x1a\x17.fujin.v1.FujinResponse(\x010\x01B/Z-github.com/ValerySidorin/fujin/public/grpc/v1b\x06proto3"

var (
	file_public_grpc_v1_fujin_proto_rawDescOnce sync.Once
	file_public_grpc_v1_fujin_proto_rawDescData []byte
)

func file_public_grpc_v1_fujin_proto_rawDescGZIP() []byte {
	file_public_grpc_v1_fujin_proto_rawDescOnce.Do(func() {
		file_public_grpc_v1_fujin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_public_grpc_v1_fujin_proto_rawDesc), len(file_public_grpc_v1_fujin_proto_rawDesc)))
	})
	return file_public_grpc_v1_fujin_proto_rawDescData
}

var file_public_grpc_v1_fujin_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_public_grpc_v1_fujin_proto_goTypes = []any{
	(*Header)(nil),              // 0: fujin.v1.Header
	(*ConnectRequest)(nil),      // 1: fujin.v1.ConnectRequest
	(*ConnectResponse)(nil),     // 2: fujin.v1.ConnectResponse
	(*ProduceRequest)(nil),      // 3: fujin.v1.ProduceRequest
	(*ProduceResponse)(nil),     // 4: fujin.v1.ProduceResponse
	(*SubscribeRequest)(nil),    // 5: fujin.v1.SubscribeRequest
	(*SubscribeResponse)(nil),   // 6: fujin.v1.SubscribeResponse
	(*UnsubscribeRequest)(nil),  // 7: fujin.v1.UnsubscribeRequest
	(*UnsubscribeResponse)(nil), // 8: fujin.v1.UnsubscribeResponse
	(*Message)(nil),             // 9: fujin.v1.Message
	(*AckRequest)(nil),          // 10: fujin.v1.AckRequest
	(*NackRequest)(nil),         // 11: fujin.v1.NackRequest
	(*Empty)(nil),               // 12: fujin.v1.Empty
	(*FujinRequest)(nil),        // 13: fujin.v1.FujinRequest
	(*FujinResponse)(nil),       // 14: fujin.v1.FujinResponse
}
var file_public_grpc_v1_fujin_proto_depIdxs = []int32{
	0,  // 0: fujin.v1.ProduceRequest.headers:type_name -> fujin.v1.Header
	0,  // 1: fujin.v1.SubscribeRequest.headers:type_name -> fujin.v1.Header
	0,  // 2: fujin.v1.Message.headers:type_name -> fujin.v1.Header
	1,  // 3: fujin.v1.FujinRequest.connect:type_name -> fujin.v1.ConnectRequest
	3,  // 4: fujin.v1.FujinRequest.produce:type_name -> fujin.v1.ProduceRequest
	5,  // 5: fujin.v1.FujinRequest.subscribe:type_name -> fujin.v1.SubscribeRequest
	7,  // 6: fujin.v1.FujinRequest.unsubscribe:type_name -> fujin.v1.UnsubscribeRequest
	10, // 7: fujin.v1.FujinRequest.ack:type_name -> fujin.v1.AckRequest
	11, // 8: fujin.v1.FujinRequest.nack:type_name -> fujin.v1.NackRequest
	2,  // 9: fujin.v1.FujinResponse.connect:type_name -> fujin.v1.ConnectResponse
	4,  // 10: fujin.v1.FujinResponse.produce:type_name -> fujin.v1.ProduceResponse
	6,  // 11: fujin.v1.FujinResponse.subscribe:type_name -> fujin.v1.SubscribeResponse
	8,  // 12: fujin.v1.FujinResponse.unsubscribe:type_name -> fujin.v1.UnsubscribeResponse
	9,  // 13: fujin.v1.FujinResponse.message:type_name -> fujin.v1.Message
	12, // 14: fujin.v1.FujinResponse.ack:type_name -> fujin.v1.Empty
	12, // 15: fujin.v1.FujinResponse.nack:type_name -> fujin.v1.Empty
	13, // 16: fujin.v1.FujinService.Stream:input_type -> fujin.v1.FujinRequest
	14, // 17: fujin.v1.FujinService.Stream:output_type -> fujin.v1.FujinResponse
	17, // [17:18] is the sub-list for method output_type
	16, // [16:17] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_public_grpc_v1_fujin_proto_init() }
func file_public_grpc_v1_fujin_proto_init() {
	if File_public_grpc_v1_fujin_proto != nil {
		return
	}
	file_public_grpc_v1_fujin_proto_msgTypes[13].OneofWrappers = []any{
		(*FujinRequest_Connect)(nil),
		(*FujinRequest_Produce)(nil),
		(*FujinRequest_Subscribe)(nil),
		(*FujinRequest_Unsubscribe)(nil),
		(*FujinRequest_Ack)(nil),
		(*FujinRequest_Nack)(nil),
	}
	file_public_grpc_v1_fujin_proto_msgTypes[14].OneofWrappers = []any{
		(*FujinResponse_Connect)(nil),
		(*FujinResponse_Produce)(nil),
		(*FujinResponse_Subscribe)(nil),
		(*FujinResponse_Unsubscribe)(nil),
		(*FujinResponse_Message)(nil),
		(*FujinResponse_Ack)(nil),
		(*FujinResponse_Nack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_grpc_v1_fujin_proto_rawDesc), len(file_public_grpc_v1_fujin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_public_grpc_v1_fujin_proto_goTypes,
		DependencyIndexes: file_public_grpc_v1_fujin_proto_depIdxs,
		MessageInfos:      file_public_grpc_v1_fujin_proto_msgTypes,
	}.Build()
	File_public_grpc_v1_fujin_proto = out.File
	file_public_grpc_v1_fujin_proto_goTypes = nil
	file_public_grpc_v1_fujin_proto_depIdxs = nil
}
