[package]
name = "fujin-middleware"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Middleware contracts for Fujin connectors and sessions"
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
fujin-connector.workspace = true
fujin-error.workspace = true
parking_lot.workspace = true
serde_json.workspace = true

[dev-dependencies]
tokio.workspace = true
