[package]
name = "fujin-connector-kafka"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Kafka connector plugin for Fujin"
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
bytes.workspace = true
fujin-connector.workspace = true
fujin-error.workspace = true
parking_lot.workspace = true
rdkafka.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[dev-dependencies]
fujin-core.workspace = true
fujin-middleware.workspace = true
